[bar.default]
background_opacity = 0.29999999329447746
center = [ "group:g1", "group:g3" ]
end = [ "group:g5", "group:g6", "group:g4" ]
margin_ends = 0
radius = 0
shadow = false
start = [ "group:g2", "bar_3" ]

    [bar.default.dead_zone.actions]
    back = "panel-toggle walpaper"
    left = "panel-toggle control-center home"
    middle = "media toggle"
    right = "settings-toggle"
    scroll_down = "workspace-switch next"
    scroll_up = "workspace-switch prev"

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "launcher", "wallpaper" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g2"
    members = [ "keybinds", "cpu", "workspaces", "active_window" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g3"
    members = [ "clock", "media" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g4"
    members = [ "battery", "brightness", "volume" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g6"
    members = [ "widget" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g5"
    members = [ "bar", "tray", "notifications" ]
    opacity = 1.0
    padding = 6.0

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[plugins]
enabled = [
    "yuuto/calculator",
    "kenn/keybind-cheatsheet",
    "rylos/tailnet",
    "pozzoo/hassio",
    "autumn/network-toolkit",
    "noctalia/notes"
]

[shell]
polkit_agent = true

[theme]
builtin = "Catppuccin"
community_palette = "Catppuccin Macchiato Lavender"
source = "community"

[wallpaper.default]
path = "/usr/share/noctalia/assets/noctalia-wallpaper.png"

[wallpaper.last]
path = "/usr/share/noctalia/assets/noctalia-wallpaper.png"

[widget.bar]
type = "rylos/tailnet:bar"

[widget.bar_3]
type = "prponkshe/umbriel-displays:bar"

[widget.clock]
anchor = true

[widget.keybinds]
type = "kenn/keybind-cheatsheet:keybinds"

[widget.network]
show_label = false

[widget.widget]
type = "autumn/network-toolkit:widget"

[widget.workspaces]
anchor = true
