[include]
files = [
    "cfg/appearance.toml",
    "cfg/keybinds.toml",
    "cfg/animation.toml",
    "cfg/display.toml",
    "cfg/input.toml",
    "cfg/layout.toml",
    "cfg/window_rule.toml",
    "cfg/autostart.toml",
]

[include.optional]
files = ["noctalia.toml"]
