[animation]
enabled = true
duration_ms = 250
curve = "easeout"

[animation.windows_in]
enabled = true
duration_ms = 240
curve = "0.3333333333,0.6666666667,0.6666666667,1"
style = "none"
shader = "../shaders/circular-iris-tl.glsl"

[animation.windows_out]
enabled = true
duration_ms = 240
curve = "0.3333333333,0.6666666667,0.6666666667,1"
style = "fade"
shader = "../shaders/circular-iris-tl.glsl"

[animation.windows_move]
enabled = true
duration_ms = 250
curve = "snappy"

[animation.workspaces]
enabled = true
duration_ms = 250
curve = "easeout"

[animation.overview]
enabled = true
duration_ms = 250
curve = "easeout"
workspace_curve = "spring:1,1000"

[animation.scratchpad]
enabled = false
duration_ms = 250
curve = "easeout"
dim = 0.5
blur = false
scale = 0.0
maximize = false
fullscreen = false

[animation.border]
enabled = false
duration_ms = 250
curve = "easeout"

[animation.dim_unfocused]
enabled = false
duration_ms = 250
curve = "easeout"
dim = 0.0

[animation.layers]
enabled = false
duration_ms = 250
curve = "easeout"
